[project]
name = "sql"
version = "0.1.0"
description = "Add your description here"
readme = "readme.adoc"
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.21.0",
    "fastmcp>=2.8.1",
]

[tool.ruff]
line-length = 100
target-version = "py311"
indent-width = 2
